FROM fholzer/nginx-brotli:v1.19.1

RUN apk update && \
    apk add --no-cache ca-certificates && \
    rm -rf /var/cache/apk/*

COPY dist /usr/share/nginx/html
COPY nginx/local.conf /etc/nginx/conf.d/default.conf

# COPY graphvizlib.wasm /usr/share/nginx/html/public/graphvizlib.wasm

COPY docker-entrypoint.sh /usr/local/bin
RUN ln -s /usr/local/bin/docker-entrypoint.sh /
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
