# SPDX-License-Identifier: Apache-2.0

# name of the action
name: ci

# trigger on pull_request or push events
on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CI: 1

# pipeline to execute
jobs:
  # ┌─┐┬  ┌┬┐   ┌─┐┌─┐┬─┐┌┬┐┌─┐┌┬┐
  # ├┤ │  │││───├┤ │ │├┬┘│││├─┤ │
  # └─┘┴─┘┴ ┴   └  └─┘┴└─┴ ┴┴ ┴ ┴
  elm-format:
    name: validate elm files
    runs-on: ubuntu-latest

    permissions:
      actions: write # for actions/cache to write to cache location

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v2-
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-v2-
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"

      - name: install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: install elm-format
        run: npm i elm-format@0.8.5
      - name: run elm-format
        run: npm run lint:elm

  # ┌─┐┬  ┌┬┐  ┌┬┐┌─┐┌─┐┌┬┐
  # ├┤ │  │││───│ ├┤ └─┐ │
  # └─┘┴─┘┴ ┴   ┴ └─┘└─┘ ┴
  elm-test:
    name: run elm tests
    runs-on: ubuntu-latest

    permissions:
      actions: write # for actions/cache to write to cache location

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-v3-${{ hashFiles('**/elm.json') }}
          restore-keys: |
            ${{ runner.os }}-elm-v3-
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v2-
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-v2-
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"

      - name: install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: install elm-test
        run: npm i elm-test@0.19.2-0
      - name: run elm-test
        run: npm run test

  # ┬  ┬┌┐┌┌┬┐
  # │  ││││ │
  # ┴─┘┴┘└┘ ┴
  lint:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      actions: write # for actions/cache to write to cache location

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v2-
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-v2-
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"

      - name: install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: run linter
        run: npm run lint

  # ┌─┐┬ ┬┌┐ ┬  ┬┌─┐┬ ┬
  # ├─┘│ │├┴┐│  │└─┐├─┤
  # ┴  └─┘└─┘┴─┘┴└─┘┴ ┴
  publish:
    name: build and push to docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'go-vela/ui'
    needs: [lint, elm-format, elm-test]

    permissions:
      actions: write # for actions/cache to write to cache location

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-v3-${{ hashFiles('**/elm.json') }}
          restore-keys: |
            ${{ runner.os }}-elm-v3-
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v2-
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-v2-
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".nvmrc"

      # ┌┐ ┬ ┬┬┬  ┌┬┐
      # ├┴┐│ │││   ││
      # └─┘└─┘┴┴─┘─┴┘
      - name: install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: run development build
        run: npm run build

      # ┌┬┐┌─┐┌─┐┬┌─┌─┐┬─┐
      #  │││ ││  ├┴┐├┤ ├┬┘
      # ─┴┘└─┘└─┘┴ ┴└─┘┴└─
      - name: login to dockerhub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: target/vela-ui
          tags: |
            # latest
            type=raw,value=latest,enable={{is_default_branch}}

      - name: build and push image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
