# Copyright (c) 2019 Target Brands, Inc. All rights reserved.
#
# Use of this source code is governed by the LICENSE file in this repository.

name: publish to docker

on:
  push:
    branches:
      - master

env:
  ELM_HOME: "${GITHUB_WORKSPACE}"
  NODE_ENV: production
  USE_NODE_VER: "10.15.3"
  CI: 1

jobs:
  publish:
    name: build and push to docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - uses: actions/setup-node@v1
        with:
          node-version: "${USE_NODE_VER}"

      # ┌┐ ┬ ┬┬┬  ┌┬┐
      # ├┴┐│ │││   ││
      # └─┘└─┘┴┴─┘─┴┘
      - name: install dependencies
        run: npm i --prefer-offline --no-audit
      - name: run production build
        run: npm run build-prod

      # ┌┬┐┌─┐┌─┐┬┌─┌─┐┬─┐
      #  │││ ││  ├┴┐├┤ ├┬┘
      # ─┴┘└─┘└─┘┴ ┴└─┘┴└─
      - name: push to docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: target/vela-ui
          cache: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
