name: elm test
on:
  pull_request:
  push:

jobs:
  elm-test:
    runs-on: ubuntu-latest
    env:
      ELM_HOME: "${GITHUB_WORKSPACE}"
      CI: 1
    steps:
      - name: clone
        uses: actions/checkout@v1

      - name: cache central npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: cache cypress binary
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-node-

      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
      - run: npm i
      - run: npm i elm-test
      - run: npm run test
