name: validate
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ELM_HOME: "${GITHUB_WORKSPACE}"
    steps:
      - name: clone
        uses: actions/checkout@v1

      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-modules-${{ hashFiles('**/package-lock.json') }}

      - name: cache home cache
        uses: actions/cache@v1
        with:
          path: "$HOME/.cache"
          key: home-dotcache-${{ hashFiles('**/package-lock.json') }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
      - run: npm i
      - run: npm i elm-format
      - run: npx elm-format --validate src/ tests/
